# version format
version: 3.2.{build}.0

os: Visual Studio 2015

artifacts:
  - path: 'build/doc/*.chm'
    name: Documentation

install:
    - cmd: >-
    7z x -y c:\projects\cpacs\development\3rdparty.zip -oc:\projects\cpacs\development\
    powershell -Command "Invoke-WebRequest https://github.com/DLR-SC/tixi/releases/download/v3.0.3/TIXI-3.0.3-win32.zip -OutFile c:\projects\cpacs-yh7xj\TIXI-3.0.3-win32.zip"
    7z x -y c:\projects\cpacs-yh7xj\TIXI-3.0.3-win32.zip -oc:\projects\cpacs-yh7xj\tools
    SET PATH=c:\projects\cpacs-yh7xj\tools\TIXI-3.0.3-win32\bin;%PATH%
    SET PYTHONPATH=c:\projects\cpacs-yh7xj\tools\TIXI-3.0.3-win32\share\tixi\python;%PYTHONPATH%
    python -V

    
platform: Any CPU

configuration: Release

build:
    project: documentation\Cpacs_doc_project.shfbproj

build_script:
- cmd: >-
    echo "running schema validation..."
    python tests/test.py
